/*
# Seed Movies Part 4 (31-40) - Iranian Cinema + More
*/
INSERT INTO movies (title_en, title_fa, slug, description_en, description_fa, poster_url, backdrop_url, trailer_url, imdb_rating, release_year, runtime, country, language, age_rating, status) VALUES
('A Separation', 'جدایی نادر از سیمین', 'a-separation', 'A married couple faces a difficult decision when one wants to leave Iran to provide a better life for their daughter.', 'یک زوج متأهل با تصمیم سختی روبرو می‌شوند وقتی یکی از آن‌ها می‌خواهد ایران را ترک کند تا زندگی بهتری برای دخترشان فراهم کند.', 'https://images.pexels.com/photos/2873486/pexels-photo-2873486.jpeg?auto=compress&cs=tinysrgb&w=500', 'https://images.pexels.com/photos/2873486/pexels-photo-2873486.jpeg?auto=compress&cs=tinysrgb&w=1280', 'https://www.youtube.com/watch?v=Q2M6M4N9q8M', 8.3, 2011, 123, 'Iran', 'fa', 'PG-13', 'published'),
('The Salesman', 'فروشنده', 'the-salesman', 'A young couple moves into a new apartment, but a former tenant unexpected return brings violence into their lives.', 'یک زوج جوان به آپارتمان جدیدی نقل مکان می‌کنند، اما بازگشت غیرمنتظره مستاجر قبلی خشونت را به زندگی آن‌ها می‌آورد.', 'https://images.pexels.com/photos/3311884/pexels-photo-3311884.jpeg?auto=compress&cs=tinysrgb&w=500', 'https://images.pexels.com/photos/3311884/pexels-photo-3311884.jpeg?auto=compress&cs=tinysrgb&w=1280', 'https://www.youtube.com/watch?v=Q2M6M4N9q8M', 7.7, 2016, 124, 'Iran', 'fa', 'PG-13', 'published'),
('About Elly', 'درباره الی', 'about-elly', 'A group of former classmates reunite for a weekend by the Caspian Sea, but a sudden disappearance changes everything.', 'گروهی از هم‌کلاسی‌های سابق برای آخر هفته در کنار دریای خزر دور هم جمع می‌شوند، اما ناپدید شدن ناگهانی همه چیز را تغییر می‌دهد.', 'https://images.pexels.com/photos/1663780/pexels-photo-1663780.jpeg?auto=compress&cs=tinysrgb&w=500', 'https://images.pexels.com/photos/1663780/pexels-photo-1663780.jpeg?auto=compress&cs=tinysrgb&w=1280', 'https://www.youtube.com/watch?v=Q2M6M4N9q8M', 8.0, 2009, 119, 'Iran', 'fa', 'PG-13', 'published'),
('The Color of Paradise', 'رنگ خدا', 'the-color-of-paradise', 'A blind father returns to his village to spend time with his son, but the boy faces rejection from his family.', 'پدر نابینا به روستایش بازمی‌گردد تا با پسرش وقت بگذراند، اما پسر با طرد از سوی خانواده روبرو می‌شود.', 'https://images.pexels.com/photos/3758956/pexels-photo-3758956.jpeg?auto=compress&cs=tinysrgb&w=500', 'https://images.pexels.com/photos/3758956/pexels-photo-3758956.jpeg?auto=compress&cs=tinysrgb&w=1280', 'https://www.youtube.com/watch?v=Q2M6M4N9q8M', 8.2, 1999, 90, 'Iran', 'fa', 'PG', 'published'),
('Children of Heaven', 'فرزندان بهشت', 'children-of-heaven', 'Two siblings share a pair of shoes after one loses the other, leading to a heartwarming journey.', 'دو خواهر و برادر پس از گم شدن کفش یکی، یک جفت کفش را به اشتراک می‌گذارند که به سفری دلگرم‌کننده منجر می‌شود.', 'https://images.pexels.com/photos/7233899/pexels-photo-7233899.jpeg?auto=compress&cs=tinysrgb&w=500', 'https://images.pexels.com/photos/7233899/pexels-photo-7233899.jpeg?auto=compress&cs=tinysrgb&w=1280', 'https://www.youtube.com/watch?v=Q2M6M4N9q8M', 8.2, 1997, 89, 'Iran', 'fa', 'PG', 'published'),
('The Past', 'گذشته', 'the-past', 'An Iranian man returns to Paris to finalize his divorce, only to discover his wife new relationship has complications.', 'مردی ایرانی به پاریس بازمی‌گردد تا طلاقش را نهایی کند، اما متوجه می‌شود رابطه جدید همسرش پیچیدگی‌هایی دارد.', 'https://images.pexels.com/photos/3945313/pexels-photo-3945313.jpeg?auto=compress&cs=tinysrgb&w=500', 'https://images.pexels.com/photos/3945313/pexels-photo-3945313.jpeg?auto=compress&cs=tinysrgb&w=1280', 'https://www.youtube.com/watch?v=Q2M6M4N9q8M', 7.9, 2013, 130, 'Iran', 'fa', 'PG-13', 'published'),
('Scarface', 'صورت‌زخمی', 'scarface', 'In 1980 Miami, a determined Cuban immigrant takes over a drug cartel and succumbs to greed.', 'در میامی ۱۹۸۰، یک مهاجر کوبایی مصمم کنترل یک کارتل مواد مخدر را به دست می‌گیرد و تسلیم طمع می‌شود.', 'https://images.pexels.com/photos/274937/pexels-photo-274937.jpeg?auto=compress&cs=tinysrgb&w=500', 'https://images.pexels.com/photos/274937/pexels-photo-274937.jpeg?auto=compress&cs=tinysrgb&w=1280', 'https://www.youtube.com/watch?v=QbB6M4N9q8M', 8.3, 1983, 170, 'USA', 'en', 'R', 'published'),
('Casino', 'کازینو', 'casino', 'A tale of greed, deception, money, power, and murder between two best friends and a trophy wife.', 'داستانی درباره طمع، فریب، پول، قدرت و قتل بین دو دوست صمیمی و یک همسر تروفی.', 'https://images.pexels.com/photos/73873/pexels-photo-73873.jpeg?auto=compress&cs=tinysrgb&w=500', 'https://images.pexels.com/photos/73873/pexels-photo-73873.jpeg?auto=compress&cs=tinysrgb&w=1280', 'https://www.youtube.com/watch?v=QbB6M4N9q8M', 8.2, 1995, 178, 'USA', 'en', 'R', 'published'),
('The Wolf of Wall Street', 'گرگ وال استریت', 'the-wolf-of-wall-street', 'Based on the true story of Jordan Belfort, from his rise to a wealthy stock-broker to his fall involving crime and corruption.', 'بر اساس داستان واقعی جردن بلفورت، از صعود او به یک کارگزار ثروتمند سهام تا سقوطش با درگیری جرم و فساد.', 'https://images.pexels.com/photos/1813273/pexels-photo-1813273.jpeg?auto=compress&cs=tinysrgb&w=500', 'https://images.pexels.com/photos/1813273/pexels-photo-1813273.jpeg?auto=compress&cs=tinysrgb&w=1280', 'https://www.youtube.com/watch?v=iszwuX1AK6A', 8.2, 2013, 180, 'USA', 'en', 'R', 'published'),
('Shutter Island', 'جزیره شاتر', 'shutter-island', 'A U.S. Marshal investigates the disappearance of a murderer who escaped from a hospital for the criminally insane.', 'یک مارشال آمریکایی ناپدید شدن قاتلی را که از بیمارستان مجرمان جنایی فرار کرده، بررسی می‌کند.', 'https://images.pexels.com/photos/1115128/pexels-photo-1115128.jpeg?auto=compress&cs=tinysrgb&w=500', 'https://images.pexels.com/photos/1115128/pexels-photo-1115128.jpeg?auto=compress&cs=tinysrgb&w=1280', 'https://www.youtube.com/watch?v=5iaD5jJ9N9M', 8.2, 2010, 138, 'USA', 'en', 'R', 'published')
ON CONFLICT (slug) DO NOTHING;
