/*
# Seed Movies Part 3 (21-30)
*/
INSERT INTO movies (title_en, title_fa, slug, description_en, description_fa, poster_url, backdrop_url, trailer_url, imdb_rating, release_year, runtime, country, language, age_rating, status) VALUES
('The Prestige', 'پرستیژ', 'the-prestige', 'After a tragic accident, two stage magicians in 1890s London engage in a bitter and increasingly dangerous rivalry.', 'پس از یک حادثه تراژیک، دو شعبده‌باز صحنه‌ای در لندن دهه ۱۸۹۰ در یک رقابت تلخ و فزاینده خطرناک درگیر می‌شوند.', 'https://images.pexels.com/photos/2872277/pexels-photo-2872277.jpeg?auto=compress&cs=tinysrgb&w=500', 'https://images.pexels.com/photos/2872277/pexels-photo-2872277.jpeg?auto=compress&cs=tinysrgb&w=1280', 'https://www.youtube.com/watch?v=o4gHCmTPrD0', 8.5, 2006, 130, 'USA', 'en', 'PG-13', 'published'),
('Memento', 'یادگاری', 'memento', 'A man with short-term memory loss attempts to track down his wife murderer.', 'مردی با از دست دادن حافظه کوتاه‌مدت سعی می‌کند قاتل همسرش را ردیابی کند.', 'https://images.pexels.com/photos/336372/pexels-photo-336372.jpeg?auto=compress&cs=tinysrgb&w=500', 'https://images.pexels.com/photos/336372/pexels-photo-336372.jpeg?auto=compress&cs=tinysrgb&w=1280', 'https://www.youtube.com/watch?v=0vS0E9uZpT0', 8.4, 2000, 113, 'USA', 'en', 'R', 'published'),
('The Departed', 'رفتگان', 'the-departed', 'An undercover cop and a mole in the police try to identify each other while infiltrating an Irish gang in Boston.', 'یک پلیس مخفی و یک نفوذی در پلیس سعی می‌کنند یکدیگر را شناسایی کنند در حالی که به یک باند ایرلندی در بوستون نفوذ می‌کنند.', 'https://images.pexels.com/photos/1643384/pexels-photo-1643384.jpeg?auto=compress&cs=tinysrgb&w=500', 'https://images.pexels.com/photos/1643384/pexels-photo-1643384.jpeg?auto=compress&cs=tinysrgb&w=1280', 'https://www.youtube.com/watch?v=auYJ3ouG3e0', 8.5, 2006, 151, 'USA', 'en', 'R', 'published'),
('Apocalypse Now', 'آپوکالیپس اکنون', 'apocalypse-now', 'A Captain is sent on a mission to assassinate a renegade Colonel who has set himself up as a god among a local tribe.', 'یک کاپیتان در ماموریتی فرستاده می‌شود تا یک سرگرد فراری را ترور کند که خود را در میان یک قبیله محلی خدا قرار داده.', 'https://images.pexels.com/photos/235615/pexels-photo-235615.jpeg?auto=compress&cs=tinysrgb&w=500', 'https://images.pexels.com/photos/235615/pexels-photo-235615.jpeg?auto=compress&cs=tinysrgb&w=1280', 'https://www.youtube.com/watch?v=IkrhkUeDCdY', 8.4, 1979, 147, 'USA', 'en', 'R', 'published'),
('No Country for Old Men', 'سرزمین هیچ‌کس برای پیرمردها', 'no-country-for-old-men', 'Violence ensues when a hunter stumbles upon a drug deal gone wrong and takes the money.', 'خشونت رخ می‌دهد وقتی یک شکارچی بر معامله مواد مخدر اشتباهی می‌رسد و پول را برمی‌دارد.', 'https://images.pexels.com/photos/1115128/pexels-photo-1115128.jpeg?auto=compress&cs=tinysrgb&w=500', 'https://images.pexels.com/photos/1115128/pexels-photo-1115128.jpeg?auto=compress&cs=tinysrgb&w=1280', 'https://www.youtube.com/watch?v=NEBVZpz_5hM', 8.2, 2007, 122, 'USA', 'en', 'R', 'published'),
('There Will Be Blood', 'خونریزی خواهد شد', 'there-will-be-blood', 'A story of family, religion, hatred, oil and madness, focusing on a turn-of-the-century prospector in the early days of the business.', 'داستانی درباره خانواده، مذهب، نفرت، نفت و دیوانگی، تمرکز بر یک جویندگر در روزهای اولیه کسب و کار.', 'https://images.pexels.com/photos/73873/pexels-photo-73873.jpeg?auto=compress&cs=tinysrgb&w=500', 'https://images.pexels.com/photos/73873/pexels-photo-73873.jpeg?auto=compress&cs=tinysrgb&w=1280', 'https://www.youtube.com/watch?v=feShpLS9jfA', 8.2, 2007, 158, 'USA', 'en', 'R', 'published'),
('Taxi Driver', 'راننده تاکسی', 'taxi-driver', 'A mentally unstable veteran works as a nighttime taxi driver in New York City, where he perceives a decadent society.', 'یک کهنه‌سرباز ناپایدار روانی به عنوان راننده تاکسی شبانه در نیویورک کار می‌کند، جایی که او جامعه‌ای فاسد را درک می‌کند.', 'https://images.pexels.com/photos/2104249/pexels-photo-2104249.jpeg?auto=compress&cs=tinysrgb&w=500', 'https://images.pexels.com/photos/2104249/pexels-photo-2104249.jpeg?auto=compress&cs=tinysrgb&w=1280', 'https://www.youtube.com/watch?v=QbFUBMGZp2A', 8.4, 1976, 114, 'USA', 'en', 'R', 'published'),
('The Grand Budapest Hotel', 'هتل گرند بوداپست', 'the-grand-budapest-hotel', 'A writer encounters the owner of an aging high-class hotel who tells him of his early years serving as a lobby boy.', 'نویسنده‌ای با صاحب یک هتل قدیمی کلاس بالا روبرو می‌شود که او را از سال‌های اولیه‌اش به عنوان پسر لابی می‌گوید.', 'https://images.pexels.com/photos/1323550/pexels-photo-1323550.jpeg?auto=compress&cs=tinysrgb&w=500', 'https://images.pexels.com/photos/1323550/pexels-photo-1323550.jpeg?auto=compress&cs=tinysrgb&w=1280', 'https://www.youtube.com/watch?v=1Fg5iWmQG5A', 8.3, 2014, 99, 'USA', 'en', 'R', 'published'),
('1917', '۱۹۱۷', '1917', 'Two young British soldiers are given a seemingly impossible mission during World War I.', 'دو سرباز جوان بریتانیایی در جریان جنگ جهانی اول ماموریتی به ظاهر غیرممکن دریافت می‌کنند.', 'https://images.pexels.com/photos/2259917/pexels-photo-2259917.jpeg?auto=compress&cs=tinysrgb&w=500', 'https://images.pexels.com/photos/2259917/pexels-photo-2259917.jpeg?auto=compress&cs=tinysrgb&w=1280', 'https://www.youtube.com/watch?v=YqNYrYUiMfg', 8.2, 2019, 119, 'UK', 'en', 'R', 'published'),
('Tenet', 'تنت', 'tenet', 'A secret agent is given a single word as his weapon and sent to prevent the onset of World War III.', 'یک مامور مخفی یک کلمه به عنوان سلاح خود دریافت می‌کند و برای جلوگیری از آغاز جنگ جهانی سوم فرستاده می‌شود.', 'https://images.pexels.com/photos/262045/pexels-photo-262045.jpeg?auto=compress&cs=tinysrgb&w=500', 'https://images.pexels.com/photos/262045/pexels-photo-262045.jpeg?auto=compress&cs=tinysrgb&w=1280', 'https://www.youtube.com/watch?v=L3pk_TBkihU', 7.2, 2020, 150, 'USA', 'en', 'PG-13', 'published')
ON CONFLICT (slug) DO NOTHING;
