/*
# Seed 20+ Series with Realistic Data
Populates the series table with 22 TV series featuring realistic titles, descriptions, ratings, and Pexels images.
*/
INSERT INTO series (title_en, title_fa, slug, description_en, description_fa, poster_url, backdrop_url, trailer_url, imdb_rating, release_year, country, language, age_rating, seasons, total_episodes, episode_runtime, status) VALUES
('Breaking Bad', 'بریکینگ بد', 'breaking-bad', 'A chemistry teacher diagnosed with cancer turns to manufacturing and selling methamphetamine to secure his family future.', 'معلم شیمی که به سرطان مبتلا شده، به تولید و فروش متامفتامین روی می‌آورد تا آینده خانواده‌اش را تضمین کند.', 'https://images.pexels.com/photos/2873486/pexels-photo-2873486.jpeg?auto=compress&cs=tinysrgb&w=500', 'https://images.pexels.com/photos/2873486/pexels-photo-2873486.jpeg?auto=compress&cs=tinysrgb&w=1280', 'https://www.youtube.com/watch?v=HhesaQXLuRY', 9.5, 2008, 'USA', 'en', 'TV-MA', 5, 62, 47, 'ended'),
('Game of Thrones', 'بازی تاج و تخت', 'game-of-thrones', 'Nine noble families fight for control of the lands of Westeros, while an ancient enemy returns after being dormant for millennia.', 'نه خانواده اشرافی برای کنترل سرزمین‌های وستروس می‌جنگند، در حالی که یک دشمن باستانی پس از هزاره‌ها بازمی‌گردد.', 'https://images.pexels.com/photos/1323550/pexels-photo-1323550.jpeg?auto=compress&cs=tinysrgb&w=500', 'https://images.pexels.com/photos/1323550/pexels-photo-1323550.jpeg?auto=compress&cs=tinysrgb&w=1280', 'https://www.youtube.com/watch?v=KPLWWIOCOOQ', 9.2, 2011, 'USA', 'en', 'TV-MA', 8, 73, 57, 'ended'),
('Stranger Things', 'چیزهای عجیب', 'stranger-things', 'When a young boy disappears, his mother, a police chief, and his friends must confront terrifying supernatural forces.', 'وقتی یک پسر جوان ناپدید می‌شود، مادرش، رئیس پلیس و دوستانش باید با نیروهای ماورایی ترسناک روبرو شوند.', 'https://images.pexels.com/photos/7234253/pexels-photo-7234253.jpeg?auto=compress&cs=tinysrgb&w=500', 'https://images.pexels.com/photos/7234253/pexels-photo-7234253.jpeg?auto=compress&cs=tinysrgb&w=1280', 'https://www.youtube.com/watch?v=b9EkMcueebA', 8.7, 2016, 'USA', 'en', 'TV-14', 4, 34, 51, 'ongoing'),
('The Crown', 'تاج', 'the-crown', 'Follows the political rivalries and romance of Queen Elizabeth II reign and the events that shaped the second half of the twentieth century.', 'رقیب‌های سیاسی و عاشقانه سلطنت ملکه الیزابت دوم و رویدادهایی که نیمه دوم قرن بیستم را شکل دادند را دنبال می‌کند.', 'https://images.pexels.com/photos/7233899/pexels-photo-7233899.jpeg?auto=compress&cs=tinysrgb&w=500', 'https://images.pexels.com/photos/7233899/pexels-photo-7233899.jpeg?auto=compress&cs=tinysrgb&w=1280', 'https://www.youtube.com/watch?v=JWtnJjn6ngs', 8.6, 2016, 'UK', 'en', 'TV-MA', 6, 60, 55, 'ended'),
('The Last of Us', 'آخرین بازمانده', 'the-last-of-us', 'After a global pandemic destroys civilization, a hardened survivor takes charge of a 14-year-old girl who may be humanity last hope.', 'پس از یک پاندمی جهانی که تمدن را نابود می‌کند، یک بازمانده سخت‌گیر از یک دختر ۱۴ ساله مراقبت می‌کند که ممکن است آخرین امید بشریت باشد.', 'https://images.pexels.com/photos/3758956/pexels-photo-3758956.jpeg?auto=compress&cs=tinysrgb&w=500', 'https://images.pexels.com/photos/3758956/pexels-photo-3758956.jpeg?auto=compress&cs=tinysrgb&w=1280', 'https://www.youtube.com/watch?v=uLtkt8BonwM', 8.8, 2023, 'USA', 'en', 'TV-MA', 1, 9, 60, 'ongoing'),
('Succession', 'وراثت', 'succession', 'The Roy family is known for controlling the biggest media and entertainment company in the world.', 'خانواده روی برای کنترل بزرگ‌ترین شرکت رسانه‌ای و سرگرمی جهان شناخته می‌شوند.', 'https://images.pexels.com/photos/1813273/pexels-photo-1813273.jpeg?auto=compress&cs=tinysrgb&w=500', 'https://images.pexels.com/photos/1813273/pexels-photo-1813273.jpeg?auto=compress&cs=tinysrgb&w=1280', 'https://www.youtube.com/watch?v=OzYxu_vmnoE', 8.9, 2018, 'USA', 'en', 'TV-MA', 4, 39, 60, 'ended'),
('The Mandalorian', 'ماندالورین', 'the-mandalorian', 'The travels of a lone bounty hunter in the outer reaches of the galaxy, far from the authority of the New Republic.', 'سفر یک شکارچی جایزه تنها در مناطق دورافتاده کهکشان، دور از اقتدار جمهوری جدید.', 'https://images.pexels.com/photos/7234329/pexels-photo-7234329.jpeg?auto=compress&cs=tinysrgb&w=500', 'https://images.pexels.com/photos/7234329/pexels-photo-7234329.jpeg?auto=compress&cs=tinysrgb&w=1280', 'https://www.youtube.com/watch?v=aOC8E8z_ifw', 8.7, 2019, 'USA', 'en', 'TV-14', 3, 24, 40, 'ongoing'),
('Better Call Saul', 'بهتره با ساول تماس بگیری', 'better-call-saul', 'The trials and tribulations of criminal lawyer Jimmy McGill before he became Breaking Bad Saul Goodman.', 'محنیت‌ها و سختی‌های وکیل جنایی جیمی مک‌گیل قبل از اینکه به ساول گودمن بریکینگ بد تبدیل شود.', 'https://images.pexels.com/photos/3311884/pexels-photo-3311884.jpeg?auto=compress&cs=tinysrgb&w=500', 'https://images.pexels.com/photos/3311884/pexels-photo-3311884.jpeg?auto=compress&cs=tinysrgb&w=1280', 'https://www.youtube.com/watch?v=HHN7N0U7GPQ', 8.9, 2015, 'USA', 'en', 'TV-MA', 6, 63, 47, 'ended'),
('Westworld', 'وست‌ورلد', 'westworld', 'A series inspired by the 1973 film, set at a futuristic theme park populated by artificial beings.', 'سریالی الهام گرفته از فیلم ۱۹۷۳، در یک پارک موضوعی آینده‌نگرانه که توسط موجودات مصنوعی سکونت دارد.', 'https://images.pexels.com/photos/262045/pexels-photo-262045.jpeg?auto=compress&cs=tinysrgb&w=500', 'https://images.pexels.com/photos/262045/pexels-photo-262045.jpeg?auto=compress&cs=tinysrgb&w=1280', 'https://www.youtube.com/watch?v=eX3uUll5Vxg', 8.5, 2016, 'USA', 'en', 'TV-MA', 4, 36, 60, 'ended'),
('The Boys', 'پسرها', 'the-boys', 'A group of vigilantes set out to take down corrupt superheroes who abuse their superpowers.', 'گروهی از خودجوشان عزم می‌کنند تا ابرقهرمانان فاسدی که از ابرقدرت‌های خود سوءاستفاده می‌کنند را سرنگون کنند.', 'https://images.pexels.com/photos/7234258/pexels-photo-7234258.jpeg?auto=compress&cs=tinysrgb&w=500', 'https://images.pexels.com/photos/7234258/pexels-photo-7234258.jpeg?auto=compress&cs=tinysrgb&w=1280', 'https://www.youtube.com/watch?v=M1bhOaLV4FU', 8.7, 2019, 'USA', 'en', 'TV-MA', 4, 32, 60, 'ongoing'),
('Chernobyl', 'چرنوبیل', 'chernobyl', 'In April 1986, an explosion at the Chernobyl nuclear power plant becomes one of the world worst man-made catastrophes.', 'در آوریل ۱۹۸۶، انفجار در نیروگاه هسته‌ای چرنوبیل به یکی از بدترین فجایع انسانی جهان تبدیل می‌شود.', 'https://images.pexels.com/photos/2259917/pexels-photo-2259917.jpeg?auto=compress&cs=tinysrgb&w=500', 'https://images.pexels.com/photos/2259917/pexels-photo-2259917.jpeg?auto=compress&cs=tinysrgb&w=1280', 'https://www.youtube.com/watch?v=s9APLXM9EiE', 9.4, 2019, 'UK', 'en', 'TV-MA', 1, 5, 60, 'ended'),
('True Detective', 'کارآگاه حقیقی', 'true-detective', 'An anthology series in which police investigations unearth the personal and professional secrets of those involved.', 'سریال آنتولوژی که در آن تحقیقات پلیسی اسرار شخصی و حرفه‌ای درگیران را آشکار می‌کند.', 'https://images.pexels.com/photos/1115128/pexels-photo-1115128.jpeg?auto=compress&cs=tinysrgb&w=500', 'https://images.pexels.com/photos/1115128/pexels-photo-1115128.jpeg?auto=compress&cs=tinysrgb&w=1280', 'https://www.youtube.com/watch?v=rxKWqycqBf0', 8.9, 2014, 'USA', 'en', 'TV-MA', 4, 24, 55, 'ongoing'),
('Peaky Blinders', 'پیکی بلایندرز', 'peaky-blinders', 'A gangster family epic set in 1900s England, centering on a gang who sew razor blades in the peaks of their caps.', 'حماسه خانواده گانگستری در انگلستان دهه ۱۹۰۰، تمرکز بر باندی که تیغ‌های ریش‌تراش در لبه کلاه‌های خود می‌دوزند.', 'https://images.pexels.com/photos/1643384/pexels-photo-1643384.jpeg?auto=compress&cs=tinysrgb&w=500', 'https://images.pexels.com/photos/1643384/pexels-photo-1643384.jpeg?auto=compress&cs=tinysrgb&w=1280', 'https://www.youtube.com/watch?v=oVzVdvGIC7U', 8.8, 2013, 'UK', 'en', 'TV-MA', 6, 36, 60, 'ended'),
('The Witcher', 'ویچر', 'the-witcher', 'Geralt of Rivia, a solitary monster hunter, struggles to find his place in a world where people often prove more wicked than beasts.', 'گرالت ریویا، شکارچی هیولای منزوی، برای یافتن جایگاه خود در جهانی که مردم اغلب از هیولاها شرورتر هستند تلاش می‌کند.', 'https://images.pexels.com/photos/2104249/pexels-photo-2104249.jpeg?auto=compress&cs=tinysrgb&w=500', 'https://images.pexels.com/photos/2104249/pexels-photo-2104249.jpeg?auto=compress&cs=tinysrgb&w=1280', 'https://www.youtube.com/watch?v=ndl1W4ltcmY', 8.2, 2019, 'USA', 'en', 'TV-MA', 3, 24, 60, 'ongoing'),
('House of the Dragon', 'خانه اژدها', 'house-of-the-dragon', 'The Targaryen civil war, known as the Dance of the Dragons, set 200 years before the events of Game of Thrones.', 'جنگ داخلی تارگرین، معروف به رقص اژدهاها، ۲۰۰ سال قبل از رویدادهای بازی تاج و تخت.', 'https://images.pexels.com/photos/1323550/pexels-photo-1323550.jpeg?auto=compress&cs=tinysrgb&w=500', 'https://images.pexels.com/photos/1323550/pexels-photo-1323550.jpeg?auto=compress&cs=tinysrgb&w=1280', 'https://www.youtube.com/watch?v=DotnJ7tTA34', 8.5, 2022, 'USA', 'en', 'TV-MA', 2, 18, 60, 'ongoing'),
('Dark', 'تاریک', 'dark', 'A family saga with a supernatural twist, set in a German town where the disappearance of two young children exposes the relationships among four families.', 'حماسه خانوادگی با پیچش ماورایی، در شهر آلمانی که ناپدید شدن دو کودک روابط چهار خانواده را آشکار می‌کند.', 'https://images.pexels.com/photos/1115128/pexels-photo-1115128.jpeg?auto=compress&cs=tinysrgb&w=500', 'https://images.pexels.com/photos/1115128/pexels-photo-1115128.jpeg?auto=compress&cs=tinysrgb&w=1280', 'https://www.youtube.com/watch?v=rrwycJ08zPs', 8.8, 2017, 'Germany', 'de', 'TV-MA', 3, 26, 60, 'ended'),
('The Sopranos', 'سوپرانوز', 'the-sopranos', 'A New Jersey mob boss, Tony Soprano, deals with personal and professional issues in his home and business life.', 'رئیس مافیای نیوجرسی، تونی سوپرانو، با مشکلات شخصی و حرفه‌ای در زندگی خانگی و تجاری خود مقابله می‌کند.', 'https://images.pexels.com/photos/274937/pexels-photo-274937.jpeg?auto=compress&cs=tinysrgb&w=500', 'https://images.pexels.com/photos/274937/pexels-photo-274937.jpeg?auto=compress&cs=tinysrgb&w=1280', 'https://www.youtube.com/watch?v=Q2M6M4N9q8M', 9.2, 1999, 'USA', 'en', 'TV-MA', 6, 86, 55, 'ended'),
('Fargo', 'فارگو', 'fargo', 'Various chronicles of deception, intrigue and murder in and around frozen Minnesota.', 'روایت‌های مختلف فریب، توطئه و قتل در اطراف مینه‌سوتای یخ‌زده.', 'https://images.pexels.com/photos/336372/pexels-photo-336372.jpeg?auto=compress&cs=tinysrgb&w=500', 'https://images.pexels.com/photos/336372/pexels-photo-336372.jpeg?auto=compress&cs=tinysrgb&w=1280', 'https://www.youtube.com/watch?v=Q2M6M4N9q8M', 8.9, 2014, 'USA', 'en', 'TV-MA', 5, 51, 60, 'ongoing'),
('Mindhunter', 'مایندهانتر', 'mindhunter', 'In the late 1970s, two FBI agents expand criminal science by delving into the psychology of murder.', 'در اواخر دهه ۱۹۷۰، دو مامور اف‌بی‌آی علم جنایی را با غوص در روانشناسی قتل گسترش می‌دهند.', 'https://images.pexels.com/photos/2872277/pexels-photo-2872277.jpeg?auto=compress&cs=tinysrgb&w=500', 'https://images.pexels.com/photos/2872277/pexels-photo-2872277.jpeg?auto=compress&cs=tinysrgb&w=1280', 'https://www.youtube.com/watch?v=Q2M6M4N9q8M', 8.6, 2017, 'USA', 'en', 'TV-MA', 2, 19, 60, 'ended'),
('Ozark', 'اوزارک', 'ozark', 'A financial adviser drags his family to the Missouri Ozarks, where he must launder money to appease a drug boss.', 'مشاور مالی خانواده‌اش را به اوزارک میسوری می‌کشاند، جایی که باید پول بشوید تا رئیس مواد مخدر را راضی کند.', 'https://images.pexels.com/photos/73873/pexels-photo-73873.jpeg?auto=compress&cs=tinysrgb&w=500', 'https://images.pexels.com/photos/73873/pexels-photo-73873.jpeg?auto=compress&cs=tinysrgb&w=1280', 'https://www.youtube.com/watch?v=5hBXV1V1V1V', 8.5, 2017, 'USA', 'en', 'TV-MA', 4, 44, 60, 'ended'),
('The Capital', 'پایتخت', 'the-capital-series', 'Iran most beloved comedy series follows the misadventures of Naqi and Arastoo as they navigate life in modern Tehran.', 'محبوب‌ترین سریال کمدی ایران که بدشانسی‌های نقی و ارستو را در ناوبری زندگی در تهران مدرن دنبال می‌کند.', 'https://images.pexels.com/photos/1643384/pexels-photo-1643384.jpeg?auto=compress&cs=tinysrgb&w=500', 'https://images.pexels.com/photos/1643384/pexels-photo-1643384.jpeg?auto=compress&cs=tinysrgb&w=1280', 'https://www.youtube.com/watch?v=Q2M6M4N9q8M', 9.1, 2011, 'Iran', 'fa', 'TV-PG', 7, 100, 45, 'ongoing'),
('Shahrazad', 'شهرزاد', 'shahrazad-series', 'Set in 1950s Iran, this sweeping romantic drama tells the story of Shahrazad, a young woman whose love story defies the conventions of her time.', 'در ایران دهه ۱۹۵۰، این درام عاشقانه گسترده داستان شهرزاد را روایت می‌کند، زن جوانی که داستان عشق او قراردادهای زمانه خود را به چالش می‌کشد.', 'https://images.pexels.com/photos/2872277/pexels-photo-2872277.jpeg?auto=compress&cs=tinysrgb&w=500', 'https://images.pexels.com/photos/2872277/pexels-photo-2872277.jpeg?auto=compress&cs=tinysrgb&w=1280', 'https://www.youtube.com/watch?v=Q2M6M4N9q8M', 8.8, 2015, 'Iran', 'fa', 'TV-14', 3, 60, 55, 'completed')
ON CONFLICT (slug) DO NOTHING;
