/*
# Seed Movies Part 1 (1-10)
Populates 10 movies with realistic data, posters, backdrops, trailers.
*/

INSERT INTO movies (title_en, title_fa, slug, description_en, description_fa, poster_url, backdrop_url, trailer_url, imdb_rating, release_year, runtime, country, language, age_rating, status) VALUES
('Dune Part Two', 'تلماس فرقه دو', 'dune-part-two', 'Paul Atreides unites with the Fremen while seeking revenge against the conspirators who destroyed his family.', 'پل آتریدیس با فرمن‌ها متحد می‌شود در حالی که به دنبال انتقام از توطئه‌گرانی است که خانواده او را نابود کردند.', 'https://images.pexels.com/photos/7234253/pexels-photo-7234253.jpeg?auto=compress&cs=tinysrgb&w=500', 'https://images.pexels.com/photos/7234253/pexels-photo-7234253.jpeg?auto=compress&cs=tinysrgb&w=1280', 'https://www.youtube.com/watch?v=Way9Dexny3w', 8.5, 2024, 166, 'USA', 'en', 'PG-13', 'published'),
('Oppenheimer', 'اوپنهایمر', 'oppenheimer', 'The story of J. Robert Oppenheimer and his role in the development of the atomic bomb.', 'داستان جی. رابرت اوپنهایمر و نقش او در توسعه بمب اتمی.', 'https://images.pexels.com/photos/3945313/pexels-photo-3945313.jpeg?auto=compress&cs=tinysrgb&w=500', 'https://images.pexels.com/photos/3945313/pexels-photo-3945313.jpeg?auto=compress&cs=tinysrgb&w=1280', 'https://www.youtube.com/watch?v=uYPbbksJxIg', 8.3, 2023, 180, 'USA', 'en', 'R', 'published'),
('The Batman', 'بتمن', 'the-batman', 'Batman ventures into Gotham City underworld when a sadistic killer leaves behind a trail of cryptic clues.', 'بتمن به دنیای زیرزمینی گاتهام سیتی سفر می‌کند وقتی یک قاتل بی‌رحم ردپای سرنخ‌های رمزآلود بر جای می‌گذارد.', 'https://images.pexels.com/photos/7233899/pexels-photo-7233899.jpeg?auto=compress&cs=tinysrgb&w=500', 'https://images.pexels.com/photos/7233899/pexels-photo-7233899.jpeg?auto=compress&cs=tinysrgb&w=1280', 'https://www.youtube.com/watch?v=mqqft2x_Aa4', 7.8, 2022, 176, 'USA', 'en', 'PG-13', 'published'),
('Interstellar', 'میان‌ستاره‌ای', 'interstellar', 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity survival.', 'تیمی از کاوشگران از یک کرم‌چاله در فضا عبور می‌کنند تا بقای بشریت را تضمین کنند.', 'https://images.pexels.com/photos/7234329/pexels-photo-7234329.jpeg?auto=compress&cs=tinysrgb&w=500', 'https://images.pexels.com/photos/7234329/pexels-photo-7234329.jpeg?auto=compress&cs=tinysrgb&w=1280', 'https://www.youtube.com/watch?v=zSWdZVtXT7E', 8.7, 2014, 169, 'USA', 'en', 'PG-13', 'published'),
('The Dark Knight', 'شوالیه تاریکی', 'the-dark-knight', 'Batman raises the stakes in his war on crime with the help of Lt. Jim Gordon and DA Harvey Dent.', 'بتمن با کمک ستوان جیم گوردون و دادستان هاروی دنت، شرارت را در جنگ با جنایت افزایش می‌دهد.', 'https://images.pexels.com/photos/7234258/pexels-photo-7234258.jpeg?auto=compress&cs=tinysrgb&w=500', 'https://images.pexels.com/photos/7234258/pexels-photo-7234258.jpeg?auto=compress&cs=tinysrgb&w=1280', 'https://www.youtube.com/watch?v=EXeTwQW1wfg', 9.0, 2008, 152, 'USA', 'en', 'PG-13', 'published'),
('Parasite', 'انگل', 'parasite', 'A poor family schemes to become employed by a wealthy family by infiltrating their household.', 'یک خانواده فقیر برای استخدام شدن توسط یک خانواده ثروتمند، به خانه آن‌ها نفوذ می‌کنند.', 'https://images.pexels.com/photos/3758956/pexels-photo-3758956.jpeg?auto=compress&cs=tinysrgb&w=500', 'https://images.pexels.com/photos/3758956/pexels-photo-3758956.jpeg?auto=compress&cs=tinysrgb&w=1280', 'https://www.youtube.com/watch?v=5xH0HM7HUO8', 8.5, 2019, 132, 'South Korea', 'ko', 'R', 'published'),
('Inception', 'آغاز', 'inception', 'A thief who steals corporate secrets through dream-sharing technology is given the inverse task of planting an idea.', 'دزدی که اسرار شرکتی را از طریق فناوری اشتراک رویا می‌دزدد، وظیفه معکوس کاشتن یک ایده را دریافت می‌کند.', 'https://images.pexels.com/photos/1813273/pexels-photo-1813273.jpeg?auto=compress&cs=tinysrgb&w=500', 'https://images.pexels.com/photos/1813273/pexels-photo-1813273.jpeg?auto=compress&cs=tinysrgb&w=1280', 'https://www.youtube.com/watch?v=YoHD9XEInc0', 8.8, 2010, 148, 'USA', 'en', 'PG-13', 'published'),
('The Shawshank Redemption', 'رستگاری در شاوشنک', 'the-shawshank-redemption', 'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.', 'دو مرد زندانی در طول چند سال با هم پیوند برقرار می‌کنند و از طریق اعمال نیک مشترک، آرامش و نجات نهایی را پیدا می‌کنند.', 'https://images.pexels.com/photos/2873486/pexels-photo-2873486.jpeg?auto=compress&cs=tinysrgb&w=500', 'https://images.pexels.com/photos/2873486/pexels-photo-2873486.jpeg?auto=compress&cs=tinysrgb&w=1280', 'https://www.youtube.com/watch?v=6hB3S9bIaco', 9.3, 1994, 142, 'USA', 'en', 'R', 'published'),
('Pulp Fiction', 'داستان عامه‌پسند', 'pulp-fiction', 'The lives of two mob hitmen, a boxer, a gangster and his wife intertwine in four tales of violence and redemption.', 'زندگی دو قاتل مافیایی، یک بوکسور، یک گانگستر و همسرش در چهار داستان خشونت و رستگاری در هم می‌آمیزد.', 'https://images.pexels.com/photos/3311884/pexels-photo-3311884.jpeg?auto=compress&cs=tinysrgb&w=500', 'https://images.pexels.com/photos/3311884/pexels-photo-3311884.jpeg?auto=compress&cs=tinysrgb&w=1280', 'https://www.youtube.com/watch?v=s7EdQ4FqbhY', 8.9, 1994, 154, 'USA', 'en', 'R', 'published'),
('The Godfather', 'پدرخوانده', 'the-godfather', 'The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.', 'پدرسالار رو به پیری یک سلسله جنایت سازمان‌یافته، کنترل امپراتوری مخفی خود را به پسر بی‌میلش منتقل می‌کند.', 'https://images.pexels.com/photos/1663780/pexels-photo-1663780.jpeg?auto=compress&cs=tinysrgb&w=500', 'https://images.pexels.com/photos/1663780/pexels-photo-1663780.jpeg?auto=compress&cs=tinysrgb&w=1280', 'https://www.youtube.com/watch?v=sY1S34973ns', 9.2, 1972, 175, 'USA', 'en', 'R', 'published')
ON CONFLICT (slug) DO NOTHING;
