/*
# Seed Movies Part 2 (11-20)
*/
INSERT INTO movies (title_en, title_fa, slug, description_en, description_fa, poster_url, backdrop_url, trailer_url, imdb_rating, release_year, runtime, country, language, age_rating, status) VALUES
('Fight Club', 'باشگاه مبارزه', 'fight-club', 'An insomniac office worker and a soap maker form an underground fight club that evolves into something much more.', 'یک کارمند دفتری بی‌خواب و یک صابون‌ساز یک باشگاه مبارزه زیرزمینی تشکیل می‌دهند که به چیزی بسیار بیشتر تبدیل می‌شود.', 'https://images.pexels.com/photos/274937/pexels-photo-274937.jpeg?auto=compress&cs=tinysrgb&w=500', 'https://images.pexels.com/photos/274937/pexels-photo-274937.jpeg?auto=compress&cs=tinysrgb&w=1280', 'https://www.youtube.com/watch?v=qtRKdVHc-cE', 8.8, 1999, 139, 'USA', 'en', 'R', 'published'),
('Forrest Gump', 'فارست گامپ', 'forrest-gump', 'The presidencies of Kennedy and Johnson, the Vietnam War, and other events unfold from the perspective of an Alabama man with an IQ of 75.', 'ریاست جمهوری کندی و جانسون، جنگ ویتنام و رویدادهای دیگر از دیدگاه مردی از آلاباما با ضریب هوشی ۷۵ باز می‌شود.', 'https://images.pexels.com/photos/73873/pexels-photo-73873.jpeg?auto=compress&cs=tinysrgb&w=500', 'https://images.pexels.com/photos/73873/pexels-photo-73873.jpeg?auto=compress&cs=tinysrgb&w=1280', 'https://www.youtube.com/watch?v=bLvqoHBptjg', 8.8, 1994, 142, 'USA', 'en', 'PG-13', 'published'),
('The Matrix', 'ماتریکس', 'the-matrix', 'A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.', 'یک هکر کامپیوتری از شورشیان مرموز درباره ماهیت واقعی واقعیت و نقش او در جنگ علیه کنترل‌کنندگان آن می‌آموزد.', 'https://images.pexels.com/photos/1115128/pexels-photo-1115128.jpeg?auto=compress&cs=tinysrgb&w=500', 'https://images.pexels.com/photos/1115128/pexels-photo-1115128.jpeg?auto=compress&cs=tinysrgb&w=1280', 'https://www.youtube.com/watch?v=vKQi3bBA1y8', 8.7, 1999, 136, 'USA', 'en', 'R', 'published'),
('Goodfellas', 'رفقای خوب', 'goodfellas', 'The story of Henry Hill and his life in the mob, covering his relationship with his wife and his mob partners.', 'داستان هنری هیل و زندگی او در مافیا، پوشش رابطه او با همسر و شرکای مافیایش.', 'https://images.pexels.com/photos/235615/pexels-photo-235615.jpeg?auto=compress&cs=tinysrgb&w=500', 'https://images.pexels.com/photos/235615/pexels-photo-235615.jpeg?auto=compress&cs=tinysrgb&w=1280', 'https://www.youtube.com/watch?v=2ilzidi_H8E', 8.7, 1990, 146, 'USA', 'en', 'R', 'published'),
('The Lord of the Rings', 'ارباب حلقه‌ها', 'the-lord-of-the-rings', 'A meek hobbit and his companions set out on a journey to destroy a powerful ring and save Middle-earth.', 'یک هابیت فروتن و همراهانش سفری را برای نابودی یک حلقه قدرتمند و نجات سرزمین میانه آغاز می‌کنند.', 'https://images.pexels.com/photos/1323550/pexels-photo-1323550.jpeg?auto=compress&cs=tinysrgb&w=500', 'https://images.pexels.com/photos/1323550/pexels-photo-1323550.jpeg?auto=compress&cs=tinysrgb&w=1280', 'https://www.youtube.com/watch?v=v75q3FpEkeQ', 8.9, 2001, 178, 'New Zealand', 'en', 'PG-13', 'published'),
('Gladiator', 'گلادیاتور', 'gladiator', 'A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family.', 'یک ژنرال رومی سابق برای انتقام از امپراتور فاسدی که خانواده‌اش را به قتل رساند، قدم برمی‌دارد.', 'https://images.pexels.com/photos/2104249/pexels-photo-2104249.jpeg?auto=compress&cs=tinysrgb&w=500', 'https://images.pexels.com/photos/2104249/pexels-photo-2104249.jpeg?auto=compress&cs=tinysrgb&w=1280', 'https://www.youtube.com/watch?v=owK1qxDselE', 8.5, 2000, 155, 'USA', 'en', 'R', 'published'),
('Whiplash', 'شلاق', 'whiplash', 'A promising young drummer enrolls at a cut-throat music academy where his dreams of greatness are mentored by an instructor who will stop at nothing.', 'یک درامر جوان نویدبخش در یک آکادمی موسیقی بی‌رحم ثبت‌نام می‌کند جایی که رویاهای بزرگی او توسط معلمی که از هیچ چیز دست برنمی‌دارد هدایت می‌شود.', 'https://images.pexels.com/photos/1643384/pexels-photo-1643384.jpeg?auto=compress&cs=tinysrgb&w=500', 'https://images.pexels.com/photos/1643384/pexels-photo-1643384.jpeg?auto=compress&cs=tinysrgb&w=1280', 'https://www.youtube.com/watch?v=7d_jQycdQGo', 8.5, 2014, 106, 'USA', 'en', 'R', 'published'),
('Joker', 'جوکر', 'joker', 'A mentally troubled stand-up comedian embarks on a downward spiral that leads to the creation of an iconic villain.', 'یک کمدین استندآپ با مشکلات ذهنی به سمت یک سقوط آزاد می‌رود که به خلق یک شرور نمادین منجر می‌شود.', 'https://images.pexels.com/photos/1183266/pexels-photo-1183266.jpeg?auto=compress&cs=tinysrgb&w=500', 'https://images.pexels.com/photos/1183266/pexels-photo-1183266.jpeg?auto=compress&cs=tinysrgb&w=1280', 'https://www.youtube.com/watch?v=zAGVQLHvwOY', 8.4, 2019, 122, 'USA', 'en', 'R', 'published'),
('Mad Max Fury Road', 'مکس دیوانه: جاده خشم', 'mad-max-fury-road', 'In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler in search for her homeland with the aid of a group of female prisoners.', 'در یک زمین ویران پس از آخرالزمان، یک زن با کمک گروهی از زندانیان زن علیه یک حاکم مستبد شورش می‌کند تا به وطن خود بازگردد.', 'https://images.pexels.com/photos/2259917/pexels-photo-2259917.jpeg?auto=compress&cs=tinysrgb&w=500', 'https://images.pexels.com/photos/2259917/pexels-photo-2259917.jpeg?auto=compress&cs=tinysrgb&w=1280', 'https://www.youtube.com/watch?v=hEJnMQG7evw', 8.1, 2015, 120, 'Australia', 'en', 'R', 'published'),
('Blade Runner 2049', 'بلید رانر ۲۰۴۹', 'blade-runner-2049', 'A young blade runner discovers a long-buried secret that leads him to track down former blade runner Rick Deckard.', 'یک بلید رانر جوان یک راز قدیمی را کشف می‌کند که او را به ردیابی بلید رانر سابق ریک دکارد سوق می‌دهد.', 'https://images.pexels.com/photos/262045/pexels-photo-262045.jpeg?auto=compress&cs=tinysrgb&w=500', 'https://images.pexels.com/photos/262045/pexels-photo-262045.jpeg?auto=compress&cs=tinysrgb&w=1280', 'https://www.youtube.com/watch?v=gCcx85zbxz4', 8.0, 2017, 164, 'USA', 'en', 'R', 'published')
ON CONFLICT (slug) DO NOTHING;
