/*
# Seed Movies Part 5 (41-50)
*/
INSERT INTO movies (title_en, title_fa, slug, description_en, description_fa, poster_url, backdrop_url, trailer_url, imdb_rating, release_year, runtime, country, language, age_rating, status) VALUES
('Gone Girl', 'دختر گمشده', 'gone-girl', 'With his wife disappearance having become the focus of an intense media circus, a man sees the spotlight turned on him.', 'با ناپدید شدن همسرش که به تمرکز یک سیرک رسانه‌ای شدید تبدیل شده، مردی می‌بیند که نور چراغ بر او روشن می‌شود.', 'https://images.pexels.com/photos/1183266/pexels-photo-1183266.jpeg?auto=compress&cs=tinysrgb&w=500', 'https://images.pexels.com/photos/1183266/pexels-photo-1183266.jpeg?auto=compress&cs=tinysrgb&w=1280', 'https://www.youtube.com/watch?v=2-_-1n3f8tg', 8.1, 2014, 149, 'USA', 'en', 'R', 'published'),
('Se7en', 'سون', 'se7en', 'Two detectives track a serial killer who uses the seven deadly sins as his motives.', 'دو کارآگاه یک قاتل زنجیره‌ای را ردیابی می‌کنند که از هفت گناه کبیره به عنوان انگیزه خود استفاده می‌کند.', 'https://images.pexels.com/photos/336372/pexels-photo-336372.jpeg?auto=compress&cs=tinysrgb&w=500', 'https://images.pexels.com/photos/336372/pexels-photo-336372.jpeg?auto=compress&cs=tinysrgb&w=1280', 'https://www.youtube.com/watch?v=znmZoVkCjpI', 8.6, 1995, 127, 'USA', 'en', 'R', 'published'),
('The Silence of the Lambs', 'سکوت بره‌ها', 'the-silence-of-the-lambs', 'A young FBI cadet must receive the help of an incarcerated cannibal killer to catch another serial killer.', 'یک دانشجوی جوان اف‌بی‌آی باید از کمک یک قاتل آدم‌خوار زندانی برای دستگیری قاتل زنجیره‌ای دیگر استفاده کند.', 'https://images.pexels.com/photos/2872277/pexels-photo-2872277.jpeg?auto=compress&cs=tinysrgb&w=500', 'https://images.pexels.com/photos/2872277/pexels-photo-2872277.jpeg?auto=compress&cs=tinysrgb&w=1280', 'https://www.youtube.com/watch?v=W6Mm8Skeu1E', 8.6, 1991, 118, 'USA', 'en', 'R', 'published'),
('Zodiac', 'زودیاک', 'zodiac', 'A cartoonist and a reporter investigate the Zodiac killer who terrorized the San Francisco Bay Area.', 'یک کارتونیست و یک خبرنگار قاتل زودیاک را که منطقه خلیج سان فرانسیسکو را ترساند، بررسی می‌کنند.', 'https://images.pexels.com/photos/262045/pexels-photo-262045.jpeg?auto=compress&cs=tinysrgb&w=500', 'https://images.pexels.com/photos/262045/pexels-photo-262045.jpeg?auto=compress&cs=tinysrgb&w=1280', 'https://www.youtube.com/watch?v=yN6YUH9k9E8', 7.7, 2007, 157, 'USA', 'en', 'R', 'published'),
('Prisoners', 'زندانیان', 'prisoners', 'When his daughter and her friend go missing, a desperate father takes matters into his own hands.', 'وقتی دخترش و دوستش گم می‌شوند، پدر ناامید کار را به دست خود می‌گیرد.', 'https://images.pexels.com/photos/2259917/pexels-photo-2259917.jpeg?auto=compress&cs=tinysrgb&w=500', 'https://images.pexels.com/photos/2259917/pexels-photo-2259917.jpeg?auto=compress&cs=tinysrgb&w=1280', 'https://www.youtube.com/watch?v=brz0X3Qk2aM', 8.2, 2013, 153, 'USA', 'en', 'R', 'published'),
('Nightcrawler', 'شب‌گرد', 'nightcrawler', 'A driven man desperate for work discovers the high-speed world of L.A. crime journalism.', 'مردی مصمم که بی‌کار است، دنیای پرسرعت روزنامه‌نگاری جنایت لس‌آنجلس را کشف می‌کند.', 'https://images.pexels.com/photos/2104249/pexels-photo-2104249.jpeg?auto=compress&cs=tinysrgb&w=500', 'https://images.pexels.com/photos/2104249/pexels-photo-2104249.jpeg?auto=compress&cs=tinysrgb&w=1280', 'https://www.youtube.com/watch?v=ouuX9tVr3D0', 7.9, 2014, 118, 'USA', 'en', 'R', 'published'),
('Drive', 'درایو', 'drive', 'A mysterious Hollywood stuntman gets involved with dangerous criminals when he helps his neighbor.', 'یک بدل‌کار مرموز هالیوود وقتی به همسایه‌اش کمک می‌کند، با مجرمان خطرناک درگیر می‌شود.', 'https://images.pexels.com/photos/7234329/pexels-photo-7234329.jpeg?auto=compress&cs=tinysrgb&w=500', 'https://images.pexels.com/photos/7234329/pexels-photo-7234329.jpeg?auto=compress&cs=tinysrgb&w=1280', 'https://www.youtube.com/watch?v=COW5c2J7u4E', 7.8, 2011, 100, 'USA', 'en', 'R', 'published'),
('Hereditary', 'ارثی', 'hereditary', 'A grieving family is haunted by tragic and disturbing occurrences after the death of their secretive grandmother.', 'خانواده‌ای در سوگ پس از مرگ مادربزرگ رازدارشان توسط رویدادهای تراژیک و ناراحت‌کننده تسخیر می‌شوند.', 'https://images.pexels.com/photos/3758956/pexels-photo-3758956.jpeg?auto=compress&cs=tinysrgb&w=500', 'https://images.pexels.com/photos/3758956/pexels-photo-3758956.jpeg?auto=compress&cs=tinysrgb&w=1280', 'https://www.youtube.com/watch?v=V6gW7pS2J2M', 7.3, 2018, 127, 'USA', 'en', 'R', 'published'),
('Get Out', 'بیرون برو', 'get-out', 'A young African-American visits his white girlfriend parents for the weekend, where his uneasy feelings escalate to terror.', 'یک جوان آفریقایی-آمریکایی برای آخر هفته به دیدن والدین دوست‌دختر سفیدپوستش می‌رود، جایی که احساسات ناراحت‌کننده او به وحشت تبدیل می‌شود.', 'https://images.pexels.com/photos/7234258/pexels-photo-7234258.jpeg?auto=compress&cs=tinysrgb&w=500', 'https://images.pexels.com/photos/7234258/pexels-photo-7234258.jpeg?auto=compress&cs=tinysrgb&w=1280', 'https://www.youtube.com/watch?v=sR1k9x3D0Jg', 7.7, 2017, 104, 'USA', 'en', 'R', 'published'),
('Avengers Endgame', 'انتقام‌جویان: پایان بازی', 'avengers-endgame', 'After the devastating events of Infinity War, the Avengers assemble once more to reverse Thanos actions and restore balance to the universe.', 'پس از رویدادهای ویرانگر جنگ ابدیت، انتقام‌جویان دوباره جمع می‌شوند تا اقدامات تانوس را برگردانند و تعادل را به جهان بازگردانند.', 'https://images.pexels.com/photos/7234253/pexels-photo-7234253.jpeg?auto=compress&cs=tinysrgb&w=500', 'https://images.pexels.com/photos/7234253/pexels-photo-7234253.jpeg?auto=compress&cs=tinysrgb&w=1280', 'https://www.youtube.com/watch?v=TcMBFSGVi1c', 8.4, 2019, 181, 'USA', 'en', 'PG-13', 'published')
ON CONFLICT (slug) DO NOTHING;
